# Copyright (c) 2025 Tareq Mhisen

name: Pull-Request

on: pull_request

# Required permissions for publish test results
permissions:
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - board: sham_nrf52833
            application: 'app'
            artifact_suffix: 'release'
          - board: sham_nrf52833
            application: 'app'
            overlay_configs: 'debug.conf'
            artifact_suffix: 'debug'
    uses: ./.github/workflows/build.yaml
    with:
      board: ${{ matrix.board }}
      application: ${{ matrix.application }}
      overlay_configs: ${{ matrix.overlay_configs }}
      artifact_suffix: ${{ matrix.artifact_suffix }}

  code-formatting:
    uses: ./.github/workflows/code_formatting.yaml

  hitl-test:
    needs:
      - build
    uses: ./.github/workflows/hitl.yaml
